# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('age', models.PositiveIntegerField(verbose_name='age')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('is_padawan', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Candidates',
                'ordering': ('name',),
                'verbose_name': 'Candidate',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.NullBooleanField(verbose_name='question')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedi_academy.Candidate', verbose_name='candidate')),
            ],
            options={
                'verbose_name_plural': 'Exams',
                'ordering': ('candidate',),
                'verbose_name': 'Exam',
            },
        ),
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'Jedies',
                'ordering': ('name',),
                'verbose_name': 'Jedi',
            },
        ),
        migrations.CreateModel(
            name='OrderCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='order`s code')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'verbose_name': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'Planets',
                'ordering': ('name',),
                'verbose_name': 'Planet',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='content')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedi_academy.OrderCode')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'ordering': ('content',),
                'verbose_name': 'Question',
            },
        ),
        migrations.AddField(
            model_name='jedi',
            name='training_planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedi_academy.Planet', verbose_name='planet'),
        ),
        migrations.AddField(
            model_name='exam',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedi_academy.Question', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='life_planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedi_academy.Planet', verbose_name='planet'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='padawans_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jedi_academy.Jedi', verbose_name='jedi'),
        ),
    ]
